openapi: 3.0.0
info:
  title: DMS authentication service REST API
  version: '1.0'
  description: |
    REST API for the authentication service.

    This is part of the mandatory exercise.

    Diseño y Mantenimiento del Software. Grado en Ingeniería Informática, Universidad de Burgos, 2021-2022.
  contact:
    name: Universidad de Burgos
tags:
  - name: questions
    description: Question-related operations (e.g., create, edit)
  - name: answers
    description: Answer-related operations (e.g., list)
  - name: server
    description: Operations about the server itself (e.g., server status querying)
servers:
  - url: /api/v1
paths:
  '/':
      head:
      summary: Health test for the service
      operationId: dms2122backend.presentation.rest.server.health_test
      responses:
        '204':
          description: Success response (will not redirect)
          content:
            'text/plain':
              schema:
                type: string
      tags:
        - server
  /questions:
    get:
      summary: Gets a listing of questions.
      operationId: dms2122backend.presentation.rest.user.list_questions
      responses:
        '200':
          description: A list of questions.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/QuestionsFullListModel'
      tags:
        - questions
      security:
        - user_token: []
          api_key: []
  /question/new:
    # TODO





components:
  schemas:
    UserFullModel:
      type: object
      properties:
        username:
          type: string
      required:
        - username
    UserFullPasswordModel:
      allOf:
        - $ref: '#/components/schemas/UserFullModel'
        - type: object
          properties:
            password:
              type: string
          required:
            - password
    UsersFullListModel:
      type: array
      items:
        $ref: '#/components/schemas/UserFullModel'

    QuestionFullModel:
      type: object
      properties:
        title:
          type: string
        body:
          type: string
        option1:
          type: string
        option2:
          type: string
        option3:
          type: string
        correct_answer:
          type: int
        punctuation:
          type: float
        penalty:
          type: float
      required:
        - title
        - body
        - option1
        - option2
        - option3
        - correct_answer
        - punctuation
        - penalty
    QuestionsFullListModel:
      type: array
      items:
        $ref: '#/components/schemas/QuestionFullModel'

  securitySchemes:
    api_key:
      type: apiKey
      name: X-ApiKey-Auth
      in: header
      x-apikeyInfoFunc: dms2122backend.presentation.rest.security.verify_api_key



